# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: build-agent-pool

steps:
- task: Bash@3
  displayName: Shell script to echo
  inputs:
    arguments: "anyvalue"
    filePath: 'script.sh'
- task: PowerShell@2
  displayName: Powershell scipt to echo
  inputs:
    filePath: 'script.ps1'





